services:
  app:
    build: .
    container_name: gereja-app
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gereja
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5434"
volumes:
  pgdata:
